"use strict";
const STORAGE_KEY = "skd90-data-v1";
const icons = {
 home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
 clock:'<circle cx="12" cy="13" r="8"/><path d="M12 9v4l3 2M9 2h6M12 2v3m6 1 2-2"/>',
 target:'<circle cx="11" cy="13" r="8"/><circle cx="11" cy="13" r="4"/><path d="m11 13 9-10m-4 0h4v4"/>',
 chart:'<path d="M5 20V10m7 10V4m7 16V7"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',
 right:'<path d="m9 5 7 7-7 7"/>',left:'<path d="m15 5-7 7 7 7"/>',
 check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',
 dumbbell:'<path d="M6 8v8m12-8v8M3 6v12m18-12v12M6 12h12"/>',
 phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="m8 5 8 13M10 19h4"/>',
 book:'<path d="M12 5v16M3 3c4-1 7 0 9 2 2-2 5-3 9-2v16c-4-1-7 0-9 2-2-2-5-3-9-2Z"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 play:'<path d="m9 5 10 7-10 7Z" fill="currentColor" stroke-width="1"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',
 reset:'<path d="M3 11a9 9 0 1 1 2 7M3 5v6h6"/>',power:'<path d="M12 2v10m-6-7a9 9 0 1 0 12 0"/>',
 rain:'<path d="M6 14a5 5 0 1 1 2-9 6 6 0 0 1 11 3 3 3 0 0 1 0 6H6m1 3-1 3m7-3-1 3m7-3-1 3"/>',
 edit:'<path d="m14 5 5 5M4 20l5-1L21 7a2 2 0 0 0-5-5L4 15Z"/>',
 trend:'<path d="m3 18 6-8 5 5 7-11m-6 0h6v6"/>',
 fire:'<path d="M12 2c1 6-6 7-6 13a6 6 0 0 0 12 0c0-3-1-5-3-7 0 4-3 5-3 5 2-5 1-8 0-11Z"/>',
 star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 10h18m-13 5 3 3 5-5"/>',
 alert:'<circle cx="12" cy="13" r="8"/><path d="M12 9v4m0 3v.01M4 3 1 6m19-3 3 3"/>',
 trash:'<path d="M3 6h18M9 6V3h6v3m-10 0 1 15h12l1-15M10 10v7m4-7v7"/>',
 coffee:'<path d="M3 9h13v6a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5Zm13 0h2a3 3 0 0 1 0 6h-2M6 3v3m4-3v3m4-3v3M2 22h16"/>',
 plane:'<path d="m22 2-7 20-4-9L2 9Zm-11 11 7-7"/>',
 gift:'<rect x="3" y="8" width="18" height="5" rx="1"/><path d="M5 13v8h14v-8M12 8v13m0-13H7a3 3 0 1 1 3-3Zm0 0h5a3 3 0 1 0-3-3Z"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3" fill="var(--bg)"/><circle cx="16" cy="17" r="3" fill="var(--bg)"/>',
 bell:'<path d="M5 17h14l-2-4V9a5 5 0 0 0-10 0v4Zm5 4h4M12 2v2"/>',
 cloud:'<path d="M6 19a5 5 0 1 1 0-10 7 7 0 0 1 13-1 5 5 0 0 1 0 11Z"/>',
 moon:'<path d="M21 14A9 9 0 0 1 10 3a9 9 0 1 0 11 11Z"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.01"/>',
 logout:'<path d="M9 3H4v18h5m6-15 6 6-6 6m-6-6h12"/>',
 list:'<path d="M9 5h12M9 12h12M9 19h12M3 5h.01M3 12h.01M3 19h.01"/>',
 volume:'<path d="m11 4-6 5H2v6h3l6 5Zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>'
};
function icon(name,cls=""){return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.list}</svg>`;}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function shifted(key,n){const d=new Date(key+"T12:00:00");d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function dayDiff(a,b){return Math.round((Date.parse(b+"T12:00:00Z")-Date.parse(a+"T12:00:00Z"))/86400000);}
function formatDate(key,opts={day:"numeric",month:"short",year:"numeric"}){return new Date(key+"T12:00:00").toLocaleDateString("id-ID",opts);}
const blankChecks=()=>({mit:false,deep:false,habit:false,noscroll:false,review:false});
const defaults={onboarded:false,name:"Kamu",startDate:todayKey(),threshold:80,todayDate:todayKey(),today:{
  mitText:"",
  mitItems:[{text:"",done:false}],
  habitText:"Olahraga 20 menit",
  checks:blankChecks()
},goals:[{title:"Kesehatan",target:"Olahraga 3x/minggu selama 90 hari.",progress:0},{title:"Bisnis / Karier",target:"Tentukan satu pencapaian utama untuk kariermu.",progress:0},{title:"Pengembangan Diri",target:"Membaca dan belajar secara konsisten.",progress:0}],history:{},failures:[],rewards:[{days:7,text:"Ngopi di tempat favorit"},{days:30,text:"Beli buku yang diinginkan"},{days:90,text:"Hadiah besar untuk diri sendiri"}],consequences:[],review:{win:"",fail:"",why:"",improve:""},reviews:{},settings:{focusMinutes:25,theme:"light",notifications:false}};
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function toast(message){const el=document.getElementById("toast");el.textContent=saveError||message;el.classList.add("show");clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove("show"),3200);}
function nav(){const selected=["home","focus","goals","stats"].includes(route)?route:"more";return `<nav class="nav" aria-label="Navigasi utama">${[["home","home","Beranda"],["focus","clock","Fokus"],["goals","target","Target"],["stats","chart","Statistik"],["more","menu","Lainnya"]].map(([r,i,l])=>`<button class="${selected===r?"active":""}" ${selected===r?'aria-current="page"':""} onclick="go('${r}')">${icon(i)}<span>${l}</span></button>`).join("")}</nav>`;}
function shell(content,title,sub="",extra=""){return `<div class="shell"><header class="top"><div><h1 class="brand">${title}</h1>${sub?`<p class="sub">${sub}</p>`:""}</div>${extra}</header><main class="stack" id="main">${saveError?`<div class="notice" role="alert">${esc(saveError)}<button class="text-btn" onclick="exportBackup()">Unduh Backup</button></div>`:''}${content}</main>${nav()}</div>`;}
function dateStrip(label,prev,next,disableNext=false){return `<div class="date-strip"><button class="icon-btn" aria-label="Periode sebelumnya" onclick="${prev}">${icon("left")}</button><span>${label}</span><button class="icon-btn" aria-label="Periode berikutnya" onclick="${next}" ${disableNext?"disabled":""}>${icon("right")}</button></div>`;}
function checkRow(key,title,small,ico){const d=selectedDay(),done=d.checks[key];return `<button class="checkrow" role="checkbox" aria-checked="${done}" onclick="toggleCheck('${key}')"><span class="icon-disc">${icon(ico)}</span><span class="label"><b>${title}</b><small>${esc(small)}</small></span><span class="check ${done?"done":""}">${done?icon("check"):""}</span></button>`;}
function field(label,name,value="",type="text",attrs=""){return `<label class="reviewQ"><b>${label}</b><input class="input" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function area(label,name,value=""){return `<label class="reviewQ"><b>${label}</b><textarea name="${name}" placeholder="Tulis di sini…">${esc(value)}</textarea></label>`;}
function dialogForm(title,description,body,onSubmit,label="Simpan"){const dlg=document.getElementById("dialog");dlg.innerHTML=`<h2 id="dialog-title">${title}</h2><p>${description}</p><form id="dialog-form">${body}<div class="dialog-actions"><button type="button" class="btn ghost" onclick="closeDialog()">Batal</button><button class="btn primary" type="submit">${label}</button></div></form>`;dlg.showModal();document.getElementById("dialog-form").onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.target));};}
function closeDialog(){document.getElementById("dialog").close();}
function splash(){return `<main class="splash"><div><img class="splash-logo" src="mark.svg" alt=""><h1>SKD90</h1><p class="tagline">Disiplin Hari Ini,<br>Hidup Lebih Baik Nanti.</p></div><div class="splash-footer"><button class="btn" onclick="startApp()">Mulai Sekarang ${icon("arrow")}</button><p class="footnote">Perubahan besar dimulai dari<br>langkah kecil yang konsisten.</p><small>SISTEM KENDALI DIRI · 90 HARI</small></div></main>`;}
async function notifyCompletion(){try{const options={body:"Satu langkah lebih dekat ke tujuanmu.",icon:"icon-192.png"};const registration="serviceWorker" in navigator?await navigator.serviceWorker.getRegistration():null;if(registration)await registration.showNotification("SKD90 · Fokus selesai",options);else new Notification("SKD90 · Fokus selesai",options);}catch{ /* The in-app completion message remains available. */ }}
async function toggleSound(){if(sound){sound.source.stop();sound.context.close();sound=null;render();return;}try{const ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),channel=buffer.getChannelData(0);let last=0;for(let i=0;i<channel.length;i++){last=(last+.02*(Math.random()*2-1))/1.02;channel[i]=last*3.5;}const source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=1500;const gain=ctx.createGain();gain.gain.value=.45;source.connect(filter).connect(gain).connect(ctx.destination);source.start();sound={source,context:ctx};render();}catch{toast("Audio tidak tersedia pada browser ini.");}}
function kpi(i,label,value,unit){return `<div class="kpi">${icon(i)}<div><div class="kpi-label">${label}</div><b>${value}</b><small>${unit}</small></div></div>`;}
function failure(){return shell(`<button class="btn primary full" onclick="openFailure(-1)">${icon("plus")} Catat Kegagalan</button>${data.failures.length?data.failures.map((f,i)=>`<button class="item" onclick="openFailure(${i})"><span class="icon-disc red">${icon(i%3===0?"alert":i%3===1?"phone":"list")}</span><span class="label"><b>${esc(f.what)}</b><small>${formatDate(f.date)}</small></span>${icon("right","chevron")}</button>`).join(""):`<div class="card empty"><span class="icon-disc red">${icon("book")}</span><b>Setiap pengalaman bisa jadi pelajaran.</b>Catat hal yang belum berjalan baik,<br>lalu tentukan langkah perbaikannya.</div>`}`,"Jurnal Kegagalan","Bukan untuk menghakimi, tapi belajar.");}
function openFailure(i){journalIndex=i;journalDraft={...(data.failures[i]||{date:todayKey(),what:"",why:"",repair:"",next:""})};go("detail");}
function detail(){const f=journalDraft;return `<div class="shell"><header class="top"><button class="icon-btn" aria-label="Kembali ke jurnal" onclick="go('failure')">${icon("left")}</button><h1 style="font-size:19px;letter-spacing:-.4px">${journalIndex<0?"Catat Kegagalan":"Detail Jurnal"}</h1>${journalIndex>=0?`<button class="icon-btn danger-text" aria-label="Hapus jurnal" onclick="deleteFailure()">${icon("trash")}</button>`:'<span style="width:40px"></span>'}</header><main class="stack"><div class="detail-heading"><span class="icon-disc red">${icon("alert")}</span><div><b>${esc(f.what||"Langkah baru dimulai dari refleksi")}</b><p class="mini">${formatDate(f.date)}</p></div></div><form onsubmit="saveFailure(event)">${area("1. Apa yang terjadi?","what",f.what)}${area("2. Kenapa ini terjadi?","why",f.why)}${area("3. Solusi / Perbaikan","repair",f.repair)}${area("4. Tindakan selanjutnya","next",f.next)}<button class="btn primary full" type="submit">Simpan</button></form></main>${nav()}</div>`;}
function saveFailure(e){e.preventDefault();const f={...journalDraft,...Object.fromEntries(new FormData(e.target))};if(!f.what.trim()){toast("Ceritakan dulu apa yang terjadi.");e.target.elements.what.focus();return;}if(journalIndex<0)data.failures.unshift(f);else data.failures[journalIndex]=f;save();go("failure");toast("Catatan jurnal tersimpan.");}
function deleteFailure(){dialogForm("Hapus catatan jurnal?","Catatan ini akan dihapus dari perangkat.","",()=>{data.failures.splice(journalIndex,1);save();closeDialog();go("failure");toast("Catatan dihapus.");},"Hapus");}
function rewards(){const s=calcStats(),isReward=rewardTab==="rewards",list=data[rewardTab];return shell(`<div class="tabs" role="group" aria-label="Jenis komitmen"><button class="${isReward?"active":""}" onclick="rewardTab='rewards';render()" aria-pressed="${isReward}">Reward</button><button class="${!isReward?"active":""}" onclick="rewardTab='consequences';render()" aria-pressed="${!isReward}">Konsekuensi</button></div>${list.length?list.map((r,i)=>`<button class="card reward-row" onclick="editReward(${i})" aria-label="Edit ${esc(r.text)}"><span class="check ${isReward&&s.best>=r.days?"done":""}">${isReward&&s.best>=r.days?icon("check"):""}</span><span class="icon-disc">${icon(isReward?["coffee","book","plane"][i%3]:"target")}</span><span class="label"><b>${r.days} hari ${isReward?"konsisten":"terlewat"}</b><small>${esc(r.text)}</small></span></button>`).join(""):`<div class="card empty"><b>Komitmen yang membantumu kembali.</b>Pilih konsekuensi ringan dan membangun,<br>seperti merapikan ruang kerja.</div>`}<button class="btn primary full" onclick="editReward(-1)">${icon("plus")} Tambah ${isReward?"Reward":"Konsekuensi"}</button><p class="quote">${isReward?'“Rayakan progres, sekecil apa pun.<br>Kamu sedang membangun kamu yang baru.”':"“Kembali ke proses,<br>tanpa menyalahkan diri sendiri.”"}</p>`,"Reward & Konsekuensi","Buat disiplin jadi lebih menyenangkan.");}
function editReward(i){const isReward=rewardTab==="rewards",r=data[rewardTab][i]||{days:7,text:""};dialogForm(`${i<0?"Tambah":"Edit"} ${isReward?"reward":"konsekuensi"}`,isReward?"Dibuka berdasarkan streak terbaikmu.":"Pengingat komitmen pribadi; tidak dijalankan otomatis.",field(isReward?"Jumlah hari konsisten":"Jumlah hari terlewat","days",r.days,"number",'required min="1" max="90"')+field(isReward?"Hadiah untuk dirimu":"Langkah perbaikan","text",r.text,"text",'required maxlength="180"'),f=>{const r={days:Number(f.get("days")),text:f.get("text").trim()};if(!r.text)return;if(i<0)data[rewardTab].push(r);else data[rewardTab][i]=r;save();closeDialog();render();toast("Komitmen tersimpan.");});}
function menuRow(i,text,action,right=""){return `<button class="menu-row" onclick="${action}">${icon(i)}<span class="label">${text}</span>${right?`<span class="mini">${right}</span>`:""}${icon("right","chevron")}</button>`;}
function settings(){return shell(`<div class="profile"><div class="avatar large">${icon("user")}</div><div class="profile-content"><b>${esc(data.name)}</b><p>Perjalanan 90 hari menuju versi terbaik dirimu.</p><button class="btn ghost full" onclick="editProfile()">Edit Profil</button></div></div><div>${menuRow("bell","Pengaturan Notifikasi","notificationSettings()")}${menuRow("settings","Pengaturan Habit","habitSettings()")}${menuRow("cloud","Data & Backup","backupSettings()")}${menuRow("moon","Tema","toggleTheme()",data.settings.theme==="dark"?"Gelap":"Terang")}${menuRow("info","Tentang SKD90","aboutApp()")}${menuRow("logout",'<span class="danger-text">Kembali ke layar awal</span>',"showSplash()")}</div><p class="about">Disiplin hari ini, hidup lebih baik nanti.<br>SKD90 Method v1.0</p>`,"Profil & Pengaturan");}
function toggleTheme(){data.settings.theme=data.settings.theme==="dark"?"light":"dark";save();render();}
function showSplash(){data.onboarded=false;route="home";save();render();}
function notificationSettings(){dialogForm("Notifikasi fokus","Notifikasi muncul saat sesi fokus selesai, selama aplikasi masih terbuka. Browser akan meminta izin saat diaktifkan.",`<label class="reviewQ"><b>Notifikasi sesi selesai</b><select class="input" name="enabled"><option value="false">Nonaktif</option><option value="true" ${data.settings.notifications?"selected":""}>Aktif</option></select></label>`,async f=>{if(f.get("enabled")==="true"){if(!("Notification" in window)){toast("Browser ini belum mendukung notifikasi.");return;}const p=await Notification.requestPermission();data.settings.notifications=p==="granted";if(p!=="granted")toast("Izin notifikasi belum diberikan.");}else data.settings.notifications=false;save();closeDialog();});}

const esc=escapeHtml;
