process.env.TZ='Asia/Jakarta';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function app(seed,initial='2026-09-13T09:00:00+07:00'){
  const entries=new Map(seed?[['skd90-data-v1',JSON.stringify(seed)]]:[]),elements=new Map();let now=new Date(initial).getTime();
  class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
  const document={documentElement:{dataset:{}},hidden:false,addEventListener(){},getElementById(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',classList:{add(){},remove(){}},setAttribute(){},open:false,showModal(){this.open=true;},close(){this.open=false;}});return elements.get(id);}};
  const context=vm.createContext({Date:Clock,document,window:{addEventListener(){},scrollTo(){}},navigator:{},location:{protocol:'file:'},localStorage:{getItem:k=>entries.get(k)||null,setItem:(k,v)=>entries.set(k,v)},structuredClone,Intl,console,crypto:require('node:crypto').webcrypto,setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},Blob,URL});
  for(const name of ['method.js','app.js','method-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,name),'utf8'),context,{filename:name});
  const run=s=>vm.runInContext(s,context);run(`dialogForm=(title,description,body,submit)=>{globalThis.form={title,description,body,submit};};data.onboarded=true;`);
  return {run,advance:ms=>now+=ms,entries,submit:obj=>{context.fields=new Map(Object.entries(obj));run('form.submit(fields)');},get data(){return JSON.parse(run('JSON.stringify(data)'));}};
}
test('every route renders and legacy journal/reward actions remain available',()=>{const a=app();for(const route of ['home','goals','weekly','review','stats','cycle','focus','failure','rewards','settings','more'])a.run(`go('${route}')`);a.run('openFailure(-1)');assert.equal(a.run('typeof saveFailure'), 'function');assert.equal(a.run('typeof editReward'),'function');});
test('MIT to weekly focus automatically inherits target; editing preserves ID and done state',()=>{const a=app();a.run(`data.goals=[{id:'g1',title:'Goal',target:'Result',configured:true,actual:0,desired:10,baseline:0,deadline:'2026-12-11',milestones:[],updates:[]}];data.weeklyFocus[Method.monday(todayKey())]=[{id:'w1',text:'Week',goalId:'g1'}];editMit(-1);`);a.submit({text:'Call',goalId:'',weeklyId:'w1',time:'09:00',trigger:'Coffee'});const id=a.data.today.mitItems[0].id;assert.equal(a.data.today.mitItems[0].goalId,'g1');a.run('toggleMit(0);editMit(0)');a.submit({text:'Call again',goalId:'g1',weeklyId:'w1',time:'10:00',trigger:''});assert.equal(a.data.today.mitItems[0].id,id);assert.equal(a.data.today.mitItems[0].done,true);assert.equal(a.data.goals[0].actual,0);});
test('MIT limit enforced and deleting final MIT clears category',()=>{const a=app();a.run(`data.today.mitItems=Array.from({length:5},(_,i)=>({id:'m'+i,text:'Task'+i,done:true}));syncToday();editMit(-1);`);assert.equal(a.data.today.mitItems.length,5);a.run('data.today.mitItems=[];syncToday()');assert.equal(a.data.today.checks.mit,false);});
test('timer pause/resume excludes paused minutes, completes once and can mark MIT',()=>{const a=app();a.run(`data.today.mitItems=[{id:'m1',text:'Task',done:false,goalId:''}];focusMitId='m1';toggleTimer();`);a.advance(10*60000);a.run('toggleTimer()');a.advance(5*60000);a.run('toggleTimer()');a.advance(15*60000);a.run('tick();tick();finishSession()');assert.equal(a.data.focusSessions.length,1);assert.equal(a.data.focusSessions[0].seconds,1500);assert.equal(a.data.today.checks.deep,true);a.submit({done:'yes'});assert.equal(a.data.today.mitItems[0].done,true);});
test('running timer resumes on reload and stores precisely one completed session',()=>{const a=app();a.run('toggleTimer()');a.advance(5*60000);const b=app(a.data,'2026-09-13T09:30:00+07:00');b.run('tick();tick()');assert.equal(b.data.focusSessions.length,1);assert.equal(b.data.focusSessions[0].seconds,1500);});
test('cross-midnight session allocates time by date and completion to original MIT',()=>{const a=app(null,'2026-09-13T23:50:00+07:00');a.run(`data.today.mitItems=[{id:'m1',text:'Night task',done:false}];focusMitId='m1';toggleTimer();`);a.advance(25*60000);a.run('tick()');assert.equal(a.data.focusSessions.length,2);assert.equal(a.data.focusSessions[0].seconds,600);assert.equal(a.data.focusSessions[1].seconds,900);a.submit({done:'yes'});assert.equal(a.data.history['2026-09-13'].mitItems[0].done,true);assert.equal(a.data.today.mitItems.length,0);});
test('rollover preserves incomplete MIT and history edits persist across reload',()=>{const a=app();a.run(`data.today.mitItems=[{id:'m1',text:'Pending',done:false}];syncToday();save();`);a.advance(86400000);a.run('rollover();moveDate(-1);toggleMit(0)');assert.equal(a.data.history['2026-09-13'].mitItems[0].done,true);assert.equal(a.data.today.mitItems.length,0);const b=app(a.data,'2026-09-14T09:00:00+07:00');assert.equal(b.data.history['2026-09-13'].mitItems[0].done,true);});
test('weekly decision and evening reflection save to selected period',()=>{const a=app();a.run('eveningReview()');a.submit({progress:'Meeting booked',improve:'Start earlier'});assert.equal(a.data.today.checks.review,true);assert.equal(a.data.today.evening.progress,'Meeting booked');a.run(`FormData=class {constructor(target){return new Map(Object.entries(target.fields));}};weekOffset=-1;saveReview({preventDefault(){},target:{fields:{win:'A',fail:'B',improve:'C',strategy:'change'}}});`);assert.equal(a.data.reviews['2026-08-31'].strategy,'change');});
test('first upgrade saves original data before migrating storage',()=>{const old={name:'A',startDate:'2026-09-01',todayDate:'2026-09-12',today:{mitText:'Keep me',checks:{mit:true}},goals:[],history:{},failures:[],rewards:[]};const a=app(old);assert.deepEqual(JSON.parse(a.entries.get('skd90-data-v1-before-method')),old);assert.equal(a.data.history['2026-09-12'].mitItems[0].text,'Keep me');});
test('backup restore protects previous data and keeps all five MITs',async()=>{const a=app();a.run(`data.today.mitItems=Array.from({length:5},(_,i)=>({id:'m'+i,text:'Task '+i,done:i<2}));syncToday();globalThis.backupText=JSON.stringify({format:'skd90-backup',data});data.today.mitItems=[];syncToday();save();`);await a.run(`importBackup({size:backupText.length,text:async()=>backupText})`);a.submit({});assert.equal(a.data.today.mitItems.length,5);assert.equal(a.data.today.mitItems.filter(m=>m.done).length,2);assert.ok(a.entries.get('skd90-data-v1-before-import'));const before=a.data;await a.run(`importBackup({size:2,text:async()=>'{}'})`);assert.deepEqual(a.data,before);});
test('storage failure stays visible even when action emits a success toast',()=>{const a=app();a.run(`localStorage.setItem=()=>{throw Error('Quota');};save();render();toast('Success');`);assert.match(a.run(`document.getElementById('app').innerHTML`),/Perubahan belum tersimpan/);assert.match(a.run(`document.getElementById('toast').textContent`),/Perubahan belum tersimpan/);});
test('cycle restart is gated until day 90 and keeps archived MITs and reflections',()=>{const a=app();a.run('beginNewCycle()');assert.equal(a.run('typeof form'),'undefined');a.run(`data.startDate=Method.shift(todayKey(),-89);data.today.mitItems=[{id:'a',text:'Complete',done:true}];data.cycleReview={change:'Better',learn:'Plan',carry:'Focus'};beginNewCycle();`);a.submit({});assert.equal(a.data.goals.length,0);assert.equal(a.data.today.mitItems.length,0);assert.equal(a.data.archives[0].today.mitItems[0].text,'Complete');assert.equal(a.data.archives[0].cycleReview.carry,'Focus');});
