'use strict';
let route='home',selectedDate=todayKey(),statsPeriod=90,weekOffset=0,rewardTab='rewards',journalIndex=-1,journalDraft=null,toastTimeout=null,sound=null;
let loadError='',saveError='',storageBlocked=false,archiveIndex=-1;
function loadMethod() {
  try {
    const raw=localStorage.getItem(STORAGE_KEY);
    const parsed=raw?JSON.parse(raw):{...defaults,goals:[]};
    if(raw&&parsed.schemaVersion!==Method.SCHEMA&&!localStorage.getItem(STORAGE_KEY+'-before-method'))localStorage.setItem(STORAGE_KEY+'-before-method',raw);
    return Method.migrate(parsed);
  } catch(e) {loadError='Data belum bisa dibaca. Data asli tetap tersimpan. Pulihkan backup atau unduh data asli melalui Data & Backup.';storageBlocked=true;return Method.migrate({...defaults,goals:[]});}
}
let data=loadMethod();
let timer=data.activeTimer||null,focusMode=timer?.mode||'pomodoro',focusMitId=timer?.mitId||'';
function save() {
  if(storageBlocked){toast(loadError);return false;}
  try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));saveError='';return true;}catch(e){saveError='Perubahan belum tersimpan. Unduh backup sebelum menutup aplikasi; penyimpanan browser penuh atau tidak tersedia.';toast(saveError);return false;}
}
function ensureMitItems(d){return d.mitItems || (d.mitItems=[]);}
function dayScore(d){return Method.day(d).score;}
function syncToday(){data.today=Method.day(data.today);data.history[data.todayDate]=structuredClone(data.today);}
function rollover(){if(data.todayDate===todayKey())return;syncToday();data.today=Method.day(data.history[todayKey()]||{habitText:data.today.habitText});data.todayDate=todayKey();selectedDate=todayKey();save();}
function selectedDay(){return selectedDate===data.todayDate?data.today:(data.history[selectedDate]||Method.day({habitText:data.today.habitText}));}
function editableDay(){if(selectedDate===data.todayDate)return data.today;return data.history[selectedDate]||(data.history[selectedDate]=selectedDay());}
function persistDay(){if(selectedDate===data.todayDate)syncToday();else data.history[selectedDate]=Method.day(data.history[selectedDate]);return save();}
function allHistory(){return Method.history(data);}
function calcStats(){const b=Method.bounds(data),m=Method.metrics(data,b.start,b.through);return {...Method.streaks(data),days:m.days,consistent:m.consistent,remaining:Math.max(0,dayDiff(todayKey(),b.end)+1)};}
const pct=n=>n===null?'—':n+'%';
const amount=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(n||0);
const duration=s=>`${Math.floor(s/3600)}j ${Math.floor(s%3600/60)}m`;
const goalById=id=>data.goals.find(g=>g.id===id);
const rateBar=(n,label)=>`<div class="row"><div class="progress" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${n??0}"><span style="width:${n??0}%"></span></div><b>${pct(n)}</b></div>`;
function selectField(label,name,items,value='',attrs=''){return `<label class="reviewQ"><b>${label}</b><select name="${name}" ${attrs}>${items.map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function goalOptions(){return [['','Tidak terkait target'],...data.goals.map(g=>[g.id,g.title])];}
function go(r){document.getElementById('toast').classList.remove('show');route=r;if(r==='home')selectedDate=todayKey();if(r==='cycle')archiveIndex=-1;render();window.scrollTo({top:0,behavior:'instant'});}
function moveDate(n){const next=shifted(selectedDate,n);if(next<=todayKey()){selectedDate=next;render();}}
function startApp(){data.onboarded=true;save();go('home');if(data.pendingFocus)showFocusCompletion();}
function home(){
  const d=selectedDay(),items=ensureMitItems(d),done=items.filter(m=>m.done).length,b=Method.bounds(data),day=Math.max(1,Math.min(90,dayDiff(b.start,selectedDate)+1));
  const weekly=data.weeklyFocus[Method.monday(selectedDate)]||[];
  return shell(`${loadError?`<div class="notice">${esc(loadError)}<button class="text-btn" onclick="backupSettings()">Data & Backup</button></div>`:''}
  <section class="method-banner"><span class="eyebrow">SKD90 METHOD · 1.0</span><div class="row"><b>Hari ${day} dari 90</b><button class="text-btn" onclick="go('cycle')">Review 90 Hari ${icon('right')}</button></div><p>Tindakan hari ini, hasil yang berarti.</p>${todayKey()>b.end?'<button class="btn primary full" onclick="go(\'cycle\')">Siklus selesai · lihat hasil</button>':''}</section>
  ${dateStrip(formatDate(selectedDate,{weekday:'short',day:'numeric',month:'short',year:'numeric'}),'moveDate(-1)','moveDate(1)',selectedDate>=todayKey())}
  <section class="card"><div class="row"><h3>Fokus Minggu Ini</h3><button class="text-btn" onclick="weekOffset=Math.round(dayDiff(Method.monday(todayKey()),Method.monday(selectedDate))/7);go('weekly')">Atur</button></div>${weekly.length?`<ol class="weekly-list">${weekly.map(w=>`<li>${w.done?'✓ ':''}${esc(w.text)}${w.goalId?`<small>${esc(goalById(w.goalId)?.title||'Target dihapus')}</small>`:''}</li>`).join('')}</ol>`:'<p class="mini space">Pilih hingga 3 hasil penting untuk minggu ini.</p>'}</section>
  <section class="checkrow featured mit-card"><div class="mit-head"><div><b>Tugas Utama Hari Ini (MIT)</b><small>${done} dari ${items.length} selesai · Maks. 5 tugas</small></div><button class="text-btn" onclick="editDaily()">Atur</button></div><p class="mit-intro">Apa tindakan terpenting untuk mendekati target?</p><div class="mit-list">${items.length?items.map((m,i)=>`<div class="mit-item"><span class="mit-number">${i+1}</span><div class="mit-content"><button class="mit-label ${m.done?'completed':''}" onclick="editMit(${i})">${esc(m.text)}</button><small>${esc(goalById(m.goalId)?.title||'Tidak terkait target')}${m.time?' · '+esc(m.time):''}${m.trigger?' · Setelah '+esc(m.trigger):''}</small>${m.weeklyId?`<small>↳ ${esc(weekly.find(w=>w.id===m.weeklyId)?.text||'Fokus dari minggu lain')}</small>`:''}${selectedDate===todayKey()?`<button class="text-btn" onclick="focusOn('${m.id}')">${icon('play')} Fokus</button>`:''}</div><button class="check ${m.done?'done':''}" role="checkbox" aria-checked="${m.done}" aria-label="Tugas ${i+1} selesai" onclick="toggleMit(${i})">${m.done?icon('check'):''}</button></div>`).join(''):'<p class="mini">Mulai dari 1–3 MIT utama.</p>'}</div><button class="btn soft full" onclick="editMit(-1)" ${items.length>=5?'disabled':''}>${icon('plus')} Tambah MIT</button></section>
  <div class="check-list">${checkRow('deep','Fokus Tanpa Gangguan','Deep Work · '+data.settings.focusMinutes+' menit','clock')}${checkRow('habit','Kebiasaan Utama',d.habitText,'dumbbell')}${checkRow('noscroll','Pagi Tanpa Scroll','60 menit pertama setelah bangun','phone')}<button class="checkrow" onclick="eveningReview()"><span class="icon-disc">${icon('book')}</span><span class="label"><b>Evaluasi Malam</b><small>${d.checks.review?'Refleksi tersimpan · buka kembali':'Kemajuan hari ini dan perbaikan besok'}</small></span><span class="check ${d.checks.review?'done':''}">${d.checks.review?icon('check'):''}</span></button></div>
  <section class="card progress-card"><h3>Konsistensi Harian</h3>${rateBar(dayScore(d)*20,'Lima kebiasaan harian')}<p class="mini">${dayScore(d)}/5 kebiasaan · MIT mendapat satu poin jika semuanya selesai.</p></section>`, `Halo, ${esc(data.name)} 👋`,'Jangan hanya sibuk. Bergerak menuju target.',`<button class="avatar" aria-label="Buka profil" onclick="go('settings')">${esc(data.name.slice(0,1))}</button>`);
}
function toggleMit(i){const d=editableDay();if(!d.mitItems[i])return;d.mitItems[i].done=!d.mitItems[i].done;persistDay();render();}
function toggleCheck(k){const d=editableDay();d.checks[k]=!d.checks[k];persistDay();render();}
function editDaily(){dialogForm('Rencana hari ini','Utamakan 1–3 MIT. Tambahan hingga 5 bila diperlukan.',`<div class="stack compact">${selectedDay().mitItems.map((m,i)=>`<button type="button" class="btn ghost" onclick="closeDialog();editMit(${i})">${esc(m.text)}</button>`).join('')}<button type="button" class="btn soft" onclick="closeDialog();editMit(-1)" ${selectedDay().mitItems.length>=5?'disabled':''}>Tambah MIT</button></div>`+field('Kebiasaan utama','habit',selectedDay().habitText,'text','required maxlength="150"'),f=>{editableDay().habitText=f.get('habit').trim();persistDay();closeDialog();render();});}
function editMit(i){
  const d=selectedDay();if(i<0&&d.mitItems.length>=5){toast('Maksimal 5 MIT per hari.');return;}
  const m=d.mitItems[i]||{id:Method.uid(),text:'',done:false},weekly=data.weeklyFocus[Method.monday(selectedDate)]||[];
  dialogForm(i<0?'Tambah MIT':'Edit MIT','Satu tindakan jelas yang bisa kamu kerjakan.',field('Tindakan terpenting','text',m.text,'text','required maxlength="300"')+selectField('Target terkait','goalId',goalOptions(),m.goalId)+selectField('Fokus minggu ini','weeklyId',[['','Tidak terkait fokus mingguan'],...weekly.map(w=>[w.id,w.text])],m.weeklyId)+field('Kapan? (opsional)','time',m.time,'time')+field('Setelah apa? (opsional)','trigger',m.trigger,'text','maxlength="200" placeholder="Contoh: meeting pagi"')+(i>=0?`<button type="button" class="text-btn danger-text" onclick="deleteMit(${i})">Hapus MIT</button>`:''),f=>{
    const text=f.get('text').trim();if(!text)return;
    const w=weekly.find(w=>w.id===f.get('weeklyId'));let goalId=f.get('goalId');
    if(w?.goalId&&goalId&&goalId!==w.goalId){toast('Pilih target yang sama dengan fokus mingguan.');return;}if(w?.goalId)goalId=w.goalId;
    const value={...m,text,goalId,weeklyId:w?.id||'',time:f.get('time'),trigger:f.get('trigger').trim()},target=editableDay();
    if(i<0)target.mitItems.push(value);else target.mitItems[i]=value;
    persistDay();closeDialog();render();toast('MIT tersimpan.');
  });
}
function deleteMit(i){closeDialog();dialogForm('Hapus MIT?','MIT ini juga akan dikeluarkan dari perhitungan eksekusi.', '',()=>{editableDay().mitItems.splice(i,1);persistDay();closeDialog();render();},'Hapus');}
function eveningReview(){const d=selectedDay(),m=Method.metrics(data,selectedDate,selectedDate);dialogForm('Evaluasi Malam',`${m.done}/${m.total} MIT selesai · ${m.linked} MIT terkait target · Fokus ${duration(m.seconds)}`,area('Apa kemajuan terpenting hari ini?','progress',d.evening?.progress)+area('Apa yang perlu diperbaiki besok?','improve',d.evening?.improve),f=>{if(!f.get('progress').trim()&&!f.get('improve').trim()){toast('Isi setidaknya satu refleksi.');return;}const d=editableDay();d.evening=Object.fromEntries(f);d.checks.review=true;persistDay();closeDialog();render();toast('Evaluasi malam tersimpan.');});}
function weekKey(){return shifted(Method.monday(todayKey()),weekOffset*7);}
function weekly(){const key=weekKey(),items=data.weeklyFocus[key]||[];return shell(`${dateStrip(`${formatDate(key)} – ${formatDate(shifted(key,6))}`,'weekOffset--;render()','weekOffset++;render()',key>=Method.monday(Method.bounds(data).end))}<p class="mini">Pilih maksimal 3 hasil penting. Hubungkan MIT harian ke prioritas ini.</p>${items.map((w,i)=>`<article class="card"><div class="row"><button class="check ${w.done?'done':''}" role="checkbox" aria-checked="${w.done}" aria-label="Fokus ${i+1} selesai" onclick="toggleWeekly(${i})">${w.done?icon('check'):''}</button><div class="label"><b>${esc(w.text)}</b><small>${esc(goalById(w.goalId)?.title||'Tidak terkait target')}</small></div><button class="icon-btn" aria-label="Edit fokus ${i+1}" onclick="editWeekly(${i})">${icon('edit')}</button></div></article>`).join('')}<button class="btn primary full" onclick="editWeekly(-1)" ${items.length>=3?'disabled':''}>${icon('plus')} Tambah Fokus Mingguan</button><button class="btn soft full" onclick="go('review')">Buka Review Mingguan</button>`,'Fokus Mingguan','Jembatan dari target besar ke tindakan harian.');}
function editWeekly(i){const key=weekKey(),items=data.weeklyFocus[key]||[],w=items[i]||{id:Method.uid(),text:'',goalId:'',done:false};if(i<0&&items.length>=3)return;dialogForm(i<0?'Tambah fokus mingguan':'Edit fokus mingguan','Tuliskan hasil penting yang ingin dicapai minggu ini.',field('Hasil penting minggu ini','text',w.text,'text','required maxlength="240"')+selectField('Target terkait','goalId',goalOptions(),w.goalId)+(i>=0?`<button type="button" class="text-btn danger-text" onclick="deleteWeekly(${i})">Hapus fokus mingguan</button>`:''),f=>{const text=f.get('text').trim();if(!text)return;const value={...w,text,goalId:f.get('goalId')};if(i<0)items.push(value);else items[i]=value;data.weeklyFocus[key]=items;
    // Keep existing linked MITs consistent when a weekly priority changes target.
    for(const d of Object.values(allHistory()))for(const m of d.mitItems||[])if(m.weeklyId===w.id)m.goalId=value.goalId;
    syncToday();save();closeDialog();render();});}
function toggleWeekly(i){const w=data.weeklyFocus[weekKey()]?.[i];if(w){w.done=!w.done;save();render();}}
function deleteWeekly(i){const items=data.weeklyFocus[weekKey()],id=items[i].id;closeDialog();dialogForm('Hapus fokus mingguan?','MIT tetap tersimpan; hubungannya ke fokus ini akan dilepas.','',()=>{items.splice(i,1);for(const d of Object.values(allHistory()))for(const m of d.mitItems||[])if(m.weeklyId===id)m.weeklyId='';syncToday();save();closeDialog();render();},'Hapus');}
function goals(){const b=Method.bounds(data);return shell(`<p class="mini">Result mengukur hasil nyata. Execution mengukur MIT yang diselesaikan.</p>${data.goals.map((g,i)=>{const r=Method.result(g),m=Method.metrics(data,b.start,b.through,g.id),hint=Method.diagnosis(data,g);return `<article class="card target-card"><div class="row"><span class="goal-number">${i+1}</span><h3 class="label">${esc(g.title)}</h3><button class="icon-btn" aria-label="Edit target ${esc(g.title)}" onclick="editGoal(${i})">${icon('edit')}</button></div><p class="space">${esc(g.target)}</p><small class="mini">Deadline ${formatDate(g.deadline)}</small><div class="metric-block"><span class="eyebrow">RESULT</span>${g.configured?`<p>${amount(g.actual)} / ${amount(g.desired)} ${esc(g.unit)}</p>${rateBar(r,'Result '+g.title)}`:`<p class="notice">Lengkapi ukuran hasil.${g.legacyProgress?` Progres lama: ${g.legacyProgress}% (referensi).`:''}</p>`}<button class="text-btn" onclick="${g.configured?`updateResult(${i})`:`editGoal(${i})`}">${g.configured?'Perbarui hasil':'Lengkapi target'}</button></div><div class="metric-block"><span class="eyebrow">EXECUTION</span><p>${m.done} dari ${m.total} MIT selesai</p>${rateBar(m.rate,'Execution '+g.title)}</div><div class="milestones"><div class="row"><b>Milestone · ${g.milestones.filter(x=>x.done).length}/${g.milestones.length}</b><button class="text-btn" onclick="editMilestone(${i},-1)">Tambah</button></div>${g.milestones.map((x,j)=>`<div class="row milestone"><button class="check ${x.done?'done':''}" role="checkbox" aria-checked="${x.done}" aria-label="Milestone ${esc(x.text)} selesai" onclick="toggleMilestone(${i},${j})">${x.done?icon('check'):''}</button><button class="text-btn label" onclick="editMilestone(${i},${j})">${esc(x.text)}</button></div>`).join('')}<p class="mini space">Berikutnya: ${esc(g.milestones.find(x=>!x.done)?.text||(g.milestones.length?'Semua tahap selesai':'Tambahkan tahap pertama'))}</p></div><p class="insight ${hint.tone}">${hint.label}</p></article>`;}).join('')}<button class="btn primary full" onclick="editGoal(-1)" ${data.goals.length>=3?'disabled':''}>${icon('plus')} Tambah Target</button><button class="btn soft full" onclick="weekOffset=0;go('weekly')">Atur Fokus Mingguan</button>`,'Target 90 Hari','Maksimal 3 hasil yang benar-benar berarti.');}
function editGoal(i){if(i<0&&data.goals.length>=3)return;const g=data.goals[i]||{id:Method.uid(),title:'',target:'',unit:'',actual:0,desired:0,baseline:0,deadline:Method.bounds(data).end,milestones:[],updates:[]};dialogForm(i<0?'Tambah target':'Edit target','Tentukan ukuran hasil yang meningkat dari nilai awal menuju sasaran.',field('Nama target','title',g.title,'text','required maxlength="60"')+field('Hasil yang ingin dicapai','target',g.target,'text','required maxlength="240"')+field('Satuan hasil','unit',g.unit,'text','required maxlength="30" placeholder="Rp, buku, halaman, kg turun"')+field('Nilai awal','baseline',g.baseline,'number','required min="0" step="any"')+field('Hasil aktual saat ini','actual',g.actual,'number','required min="0" step="any"')+field('Sasaran akhir','desired',g.desired||'','number','required min="0" step="any"')+field('Deadline','deadline',g.deadline,'date',`required min="${data.startDate}" max="${Method.bounds(data).end}"`)+(i>=0?`<button type="button" class="text-btn danger-text" onclick="deleteGoal(${i})">Hapus target</button>`:''),f=>{const value={...g,...Object.fromEntries(f),baseline:Number(f.get('baseline')),actual:Number(f.get('actual')),desired:Number(f.get('desired')),configured:true};if(!value.title.trim()||!value.target.trim()||!value.unit.trim())return;if(value.desired<=value.baseline){toast('Sasaran akhir harus lebih besar daripada nilai awal.');return;}if(!g.configured||g.actual!==value.actual)value.updates=[...g.updates,{date:todayKey(),actual:value.actual,note:'Pengaturan target'}];if(i<0)data.goals.push(value);else data.goals[i]=value;save();closeDialog();render();toast('Target tersimpan.');});}
function updateResult(i){const g=data.goals[i];dialogForm('Perbarui hasil',esc(g.title),field('Hasil aktual ('+esc(g.unit)+')','actual',g.actual,'number','required min="0" step="any"')+field('Catatan bukti / kemajuan (opsional)','note','','text','maxlength="300"'),f=>{g.actual=Number(f.get('actual'));g.updates.push({date:todayKey(),actual:g.actual,note:f.get('note').trim()});save();closeDialog();render();});}
function deleteGoal(i){closeDialog();dialogForm('Hapus target?','MIT dan sesi fokus tetap tersimpan. Hubungan ke target ini akan dilepas.','',()=>{const id=data.goals[i].id;data.goals.splice(i,1);for(const d of Object.values(allHistory()))for(const m of d.mitItems||[])if(m.goalId===id)m.goalId='';for(const list of Object.values(data.weeklyFocus))for(const w of list)if(w.goalId===id)w.goalId='';for(const s of data.focusSessions)if(s.goalId===id)s.goalId='';syncToday();save();closeDialog();render();},'Hapus');}
function editMilestone(i,j){const g=data.goals[i],m=g.milestones[j]||{id:Method.uid(),text:'',done:false};dialogForm('Milestone','Tahap menuju hasil. Checklist tahap tidak mengubah angka Result.',field('Tahap yang ingin dicapai','text',m.text,'text','required maxlength="240"')+(j>=0?`<button type="button" class="text-btn danger-text" onclick="data.goals[${i}].milestones.splice(${j},1);save();closeDialog();render()">Hapus milestone</button>`:''),f=>{const text=f.get('text').trim();if(!text)return;const value={...m,text};if(j<0)g.milestones.push(value);else g.milestones[j]=value;save();closeDialog();render();});}
function toggleMilestone(i,j){const m=data.goals[i].milestones[j];m.done=!m.done;save();render();}

function focusOn(id){if(timer&&timer.mitId!==id){toast('Akhiri sesi aktif sebelum berpindah MIT.');go('focus');return;}focusMitId=id;go('focus');}
function focus(){const items=data.today.mitItems,m=items.find(m=>m.id===(timer?.mitId||focusMitId));return shell(`<section class="card"><span class="eyebrow">FOKUS SEKARANG</span>${selectField('Pilih MIT','focusMit',[['','Fokus tanpa MIT'],...items.map(m=>[m.id,m.text])],timer?.mitId||focusMitId,`${timer?'disabled':''} onchange="focusMitId=this.value;render()"`)}<p class="mini">${esc(timer?.mitText||m?.text||'Satu sesi. Satu tugas. Tanpa gangguan.')}</p><small>${esc(goalById(timer?.goalId||m?.goalId)?.title||'Tidak terkait target')}</small></section><div class="tabs"><button class="${focusMode==='pomodoro'?'active':''}" onclick="setMode('pomodoro')">Pomodoro</button><button class="${focusMode==='free'?'active':''}" onclick="setMode('free')">Mode Bebas</button></div><div class="timer-wrap"><div class="timer"><svg class="timer-ring" viewBox="0 0 260 260" aria-hidden="true"><circle class="timer-track" cx="130" cy="130" r="115" stroke-dasharray="542 723"/><circle id="timer-arc" class="timer-value" cx="130" cy="130" r="115" stroke-dasharray="542 723"/></svg><div><div id="timer-digits" class="timer-digits" role="timer"></div><p id="timer-state" class="timer-state">Fokus</p></div></div><div class="timer-controls"><button class="icon-btn" aria-label="Ulangi timer" onclick="resetTimer()">${icon('reset')}</button><button class="play" id="timer-toggle" aria-label="Mulai fokus" onclick="toggleTimer()">${icon('play')}</button><button class="icon-btn" aria-label="Akhiri sesi fokus" onclick="finishSession()">${icon('power')}</button></div>${focusMode==='pomodoro'?`<div class="duration">${[25,50].map(n=>`<button class="chip ${data.settings.focusMinutes===n?'active':''}" onclick="setFocus(${n})">${n} menit</button>`).join('')}</div>`:'<p class="mini">Waktu fokus dicatat saat sesi diakhiri.</p>'}</div><p class="day-note">Sesi minimal 25 menit mencentang Fokus Tanpa Gangguan.</p>${data.pendingFocus?'<button class="btn soft" onclick="showFocusCompletion()">Sesi selesai · tandai MIT?</button>':''}<button class="card sound-card" onclick="toggleSound()"><span class="icon-disc">${icon('rain')}</span><span class="label"><b>Suara Fokus</b><small>${sound?'Hujan sedang diputar · matikan':'Hujan · putar suara'}</small></span></button>`,'Fokus Tanpa Gangguan','Hubungkan waktu fokus dengan tindakan penting.');}
function elapsedMs(t=timer,now=Date.now()){if(!t)return 0;const last=t.running?Math.max(0,now-t.startedAt):0;return t.elapsedMs+Math.min(last,t.mode==='pomodoro'?Math.max(0,t.durationMs-t.elapsedMs):last);}
function timerSeconds(){return Math.max(0,Math.ceil((focusMode==='pomodoro'?(timer?.durationMs||data.settings.focusMinutes*60000)-elapsedMs():elapsedMs())/1000));}
function updateTimerDisplay(){const el=document.getElementById('timer-digits');if(!el)return;const s=timerSeconds();el.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;document.getElementById('timer-state').textContent=timer?.running?'Sedang fokus':timer?'Dijeda':'Siap fokus';document.getElementById('timer-arc').setAttribute('stroke-dasharray',`${focusMode==='free'?542:542*(1-elapsedMs()/(timer?.durationMs||data.settings.focusMinutes*60000))} 723`);const btn=document.getElementById('timer-toggle');btn.innerHTML=icon(timer?.running?'pause':'play');btn.setAttribute('aria-label',timer?.running?'Jeda fokus':'Mulai fokus');}
function accrueTimer(){if(!timer?.running)return;const now=Date.now(),span=elapsedMs(timer,now)-timer.elapsedMs;if(span>0)timer.segments.push({start:timer.startedAt,end:timer.startedAt+span});timer.elapsedMs+=span;timer.running=false;timer.startedAt=0;}
function toggleTimer(){
  if(!timer&&data.pendingFocus){showFocusCompletion();return;}
  if(timer?.running){accrueTimer();}
  else{
    if(!timer){const m=data.today.mitItems.find(m=>m.id===focusMitId);timer={id:Method.uid(),mode:focusMode,durationMs:data.settings.focusMinutes*60000,elapsedMs:0,segments:[],mitId:m?.id||'',mitText:m?.text||'',goalId:m?.goalId||'',mitDate:todayKey(),running:false,startedAt:0};}
    timer.running=true;timer.startedAt=Date.now();
  }
  data.activeTimer=timer;save();render();
}
function stopTimer(){accrueTimer();data.activeTimer=timer;save();}
function setMode(mode){if(timer){toast('Akhiri atau ulangi sesi aktif sebelum mengubah mode.');return;}focusMode=mode;render();}
function setFocus(n){if(timer){toast('Akhiri sesi aktif sebelum mengubah durasi.');return;}data.settings.focusMinutes=n;save();render();}
function resetTimer(){if(!timer)return;dialogForm('Ulangi timer?','Waktu sesi yang belum disimpan akan dibuang.','',()=>{timer=null;delete data.activeTimer;save();closeDialog();render();},'Ulangi');}
function tick(){if(timer?.running&&timer.mode==='pomodoro'&&elapsedMs()>=timer.durationMs){accrueTimer();completeFocus();}updateTimerDisplay();}
function finishSession(){if(!timer){toast('Mulai sesi fokus terlebih dahulu.');return;}accrueTimer();completeFocus();}
function completeFocus(){
  if(!timer)return;accrueTimer();const t=timer;timer=null;delete data.activeTimer;rollover();
  // Split active intervals at local midnight; paused time never counts.
  const perDay={};for(const segment of t.segments){let pos=segment.start;while(pos<segment.end){const d=new Date(pos),date=Method.localDate(d),midnight=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).getTime(),end=Math.min(segment.end,midnight);perDay[date]=(perDay[date]||0)+(end-pos)/1000;pos=end;}}
  for(const [date,seconds] of Object.entries(perDay)){
    const id=t.id+'_'+date;
    if(!data.focusSessions.some(s=>s.id===id))data.focusSessions.push({id,date,seconds,mitId:t.mitId,goalId:t.goalId,mitText:t.mitText,mode:t.mode});
  }
  if(t.elapsedMs>=25*60000&&t.segments.length){const date=Method.localDate(new Date(t.segments.at(-1).end-1)),d=date===data.todayDate?data.today:(data.history[date]||(data.history[date]=Method.day()));d.checks.deep=true;}
  syncToday();if(t.elapsedMs>=1000)data.pendingFocus={mitId:t.mitId,mitDate:t.mitDate,seconds:t.elapsedMs/1000};save();
  const busy=document.getElementById('dialog').open||document.activeElement?.matches?.('input,textarea,select');
  if(busy){toast('Sesi fokus selesai dan tercatat. Buka Fokus untuk menandai MIT.');return;}
  render();
  if(data.settings.notifications&&'Notification' in window&&Notification.permission==='granted')notifyCompletion();
  if(data.pendingFocus)showFocusCompletion();else toast('Sesi terlalu singkat untuk dicatat.');
}
function showFocusCompletion(){const p=data.pendingFocus;if(!p)return;const day=p.mitDate===data.todayDate?data.today:data.history[p.mitDate],m=day?.mitItems.find(m=>m.id===p.mitId);const dlg=document.getElementById('dialog');if(dlg.open)closeDialog();dialogForm('Sesi selesai',`${duration(p.seconds)} fokus tercatat.`,m&&!m.done?`<p class="space">${esc(m.text)}</p>${selectField('Tandai MIT selesai?','done',[['no','Belum'],['yes','Ya']])}`:'<p class="space">Lanjutkan langkah kecilmu hari ini.</p>',f=>{if(m&&f.get('done')==='yes')m.done=true;delete data.pendingFocus;syncToday();save();closeDialog();render();},'Simpan');}
function stats(){
  const b=Method.bounds(data),end=b.through,start=[b.start,shifted(end,1-statsPeriod)].sort().at(-1),m=Method.metrics(data,start,end),s=Method.streaks(data),h=allHistory();
  const dates=Object.keys(h).filter(k=>k>=start&&k<=end),categories=[['mit','Tugas Utama (MIT)'],['deep','Fokus Tanpa Gangguan'],['habit','Kebiasaan Utama'],['noscroll','Pagi Tanpa Scroll'],['review','Evaluasi Malam']];
  const moves=data.goals.filter(g=>g.configured&&g.updates.some(u=>u.date<shifted(end,-6))).map(g=>({g,delta:Method.result(g,end)-Method.result(g,shifted(end,-7))})).sort((a,b)=>b.delta-a.delta);
  const fast=moves[0]?.delta>0?moves[0]:null;
  const attention=data.goals.filter(g=>Method.diagnosis(data,g).label!=='Pertahankan');
  const group=statsPeriod===7?1:statsPeriod===30?5:15,bars=[];for(let k=start;k<=end;k=shifted(k,group)){const x=Method.metrics(data,k,[shifted(k,group-1),end].sort()[0]);bars.push({date:k,...x});}
  return shell(`<div class="tabs">${[[7,'7 Hari'],[30,'30 Hari'],[90,'90 Hari']].map(([n,label])=>`<button class="${statsPeriod===n?'active':''}" onclick="statsPeriod=${n};render()">${label}</button>`).join('')}</div><p class="mini">${formatDate(start)} – ${formatDate(end)} · siklus aktif</p><section class="card"><span class="eyebrow">EXECUTION RATE</span><div class="rate">${pct(m.rate)}</div><p class="mini">${m.done} dari ${m.total} MIT selesai</p><div class="execution-bars" role="img" aria-label="Eksekusi per periode">${bars.map(x=>`<div><span style="height:${x.rate??0}%" title="${x.date}: ${pct(x.rate)}"></span><small>${new Date(x.date+'T12:00').getDate()}</small></div>`).join('')}</div><p class="mini">${group===1?'Per hari':`Per ${group} hari`} · hanya MIT terisi yang dihitung.</p></section><div class="grid2">${kpi('target','MIT menuju target',pct(m.linkedRate),`${m.linked}/${m.total} MIT direncanakan`)}${kpi('clock','Focus Time',duration(m.seconds),'Sesi yang tercatat')}${kpi('fire','Streak',s.streak,'hari · siklus aktif')}${kpi('calendar','Hari Konsisten',m.consistent,'hari dengan skor ≥4/5')}</div><section class="card"><h3>Pergerakan Target</h3><p class="space"><b>Bergerak paling cepat</b><br>${fast?`${esc(fast.g.title)} · +${fast.delta} poin persentase / 7 hari`:'Belum cukup riwayat perubahan hasil.'}</p><p class="space"><b>Perlu perhatian</b><br>${attention.length?attention.map(g=>esc(g.title)).join(', '):'Semua target berada pada jalurnya.'}</p>${data.goals.map(g=>`<p class="insight ${Method.diagnosis(data,g).tone}"><b>${esc(g.title)}</b> · ${Method.diagnosis(data,g).label}</p>`).join('')}<p class="mini">Insight memakai eksekusi ≥80% dan hasil dibandingkan laju waktu hingga deadline. Ini pemicu review; pertimbangkan tahap pekerjaanmu.</p></section><section class="card"><h3>Konsistensi per Kategori</h3>${categories.map(([k,label])=>{const n=dates.filter(date=>Method.day(h[date]).checks[k]).length;return `<div class="metric-block"><div class="row"><b>${label}</b><small>${n}/${dates.length} hari tercatat</small></div>${rateBar(dates.length?Math.round(n/dates.length*100):null,label)}</div>`;}).join('')}<p class="mini">Kategori MIT selesai jika semua MIT hari itu selesai. Angka kategori berbeda dari Execution Rate per tugas.</p></section>`,'90-Day Performance','Lihat arah tindakan dan hasilnya.');
}
function review(){const key=weekKey(),end=[shifted(key,6),todayKey(),Method.bounds(data).end].sort()[0],start=[key,data.startDate].sort().at(-1),m=Method.metrics(data,start,end),rev=data.reviews[key]||{};return shell(`${dateStrip(`${formatDate(key)} – ${formatDate(shifted(key,6))}`,'weekOffset--;render()','weekOffset++;render()',weekOffset>=0)}<section class="card"><span class="eyebrow">EXECUTION SCORE · MINGGU ${Math.max(1,Math.floor(dayDiff(data.startDate,key)/7)+1)}</span><div class="rate">${pct(m.rate)}</div><p>${m.done} / ${m.total} MIT selesai · ${duration(m.seconds)} fokus</p></section>${data.goals.map(g=>{const gm=Method.metrics(data,start,end,g.id),r=Method.result(g,end),u=g.updates.filter(x=>x.date<=end).at(-1);return `<section class="card"><h3>${esc(g.title)}</h3><p class="space">${gm.done} dari ${gm.total} MIT selesai · Execution ${pct(gm.rate)}</p><span class="eyebrow">RESULT PADA AKHIR PERIODE</span><p>${g.configured?`${amount(u?.actual??g.baseline)} / ${amount(g.desired)} ${esc(g.unit)}`:'Ukuran hasil belum dilengkapi'}</p>${rateBar(r,g.title)}</section>`;}).join('')}<form class="review-form" onsubmit="saveReview(event)">${area('Apa yang paling berhasil minggu ini?','win',rev.win)}${area('Apa hambatan terbesar?','fail',rev.fail)}${rev.why?`<details class="card"><summary>Catatan penyebab dari versi lama</summary><p>${esc(rev.why)}</p></details>`:''}${area('Apa yang harus saya ubah minggu depan?','improve',rev.improve)}${selectField('Strategi minggu depan','strategy',[['keep','🟢 Pertahankan'],['adjust','🟡 Sesuaikan'],['change','🔴 Ubah']],rev.strategy||'adjust')}<button class="btn primary full">Simpan Review</button></form><button class="btn soft full" onclick="weekOffset++;go('weekly')">Susun Fokus Minggu Berikutnya</button>`,'Weekly Review','Belajar dari eksekusi. Perbaiki strategi.');}
function saveReview(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(![f.win,f.fail,f.improve].some(x=>x.trim())){toast('Isi setidaknya satu refleksi.');return;}const key=weekKey();data.reviews[key]={...data.reviews[key],...f,savedAt:new Date().toISOString()};if(save())toast('Review dan keputusan strategi tersimpan.');}
function cycle(){const d=archiveIndex>=0?data.archives[archiveIndex]:data,b=Method.bounds(d),end=archiveIndex>=0?b.end:b.through,m=Method.metrics(d,b.start,end),rev=d.cycleReview||{},finished=todayKey()>=b.end;return shell(`${archiveIndex>=0?'<p class="badge">Arsip siklus · hanya baca</p>':''}<p class="mini">${formatDate(b.start)} – ${formatDate(b.end)}</p><section class="method-banner"><span class="eyebrow">90-DAY REVIEW</span><h2>${finished?'Siklus 90 Hari Selesai':'Perjalanan 90 Hari'}</h2><p>${m.consistent}/90 hari konsisten</p></section>${d.goals.map(g=>`<section class="card"><h3>${esc(g.title)}</h3><p>${g.configured?`${amount(g.actual)} / ${amount(g.desired)} ${esc(g.unit)}`:'Ukuran hasil belum dilengkapi'}</p>${rateBar(Method.result(g),g.title)}<p class="space">${Method.result(g)===100?'✅ Tercapai':Method.result(g)===null?'Lengkapi ukuran hasil':'🟡 Belum tercapai'}</p></section>`).join('')}<div class="grid2">${kpi('chart','Execution Rate',pct(m.rate),`${m.done}/${m.total} MIT`)}${kpi('clock','Focus Time',duration(m.seconds),'Sesi tercatat')}${kpi('check','MIT selesai',m.done,'tindakan')}${kpi('calendar','Hari konsisten',m.consistent,'/ 90 hari')}</div>${archiveIndex<0?`<form onsubmit="saveCycleReview(event)">${area('Apa perubahan terbesar dalam dirimu?','change',rev.change)}${area('Apa yang kamu pelajari?','learn',rev.learn)}${area('Apa yang akan kamu bawa ke 90 hari berikutnya?','carry',rev.carry)}<button class="btn primary full">Simpan Review 90 Hari</button></form><button class="btn soft full" onclick="beginNewCycle()" ${finished?'':'disabled'}>Mulai Siklus 90 Hari Baru</button>${finished?'':'<p class="mini">Siklus baru tersedia pada hari ke-90.</p>'}`:`<section class="card"><h3>Refleksi akhir</h3>${[['Perubahan terbesar',rev.change],['Pelajaran',rev.learn],['Dibawa ke siklus berikutnya',rev.carry]].map(([t,x])=>`<p class="space"><b>${t}</b><br>${esc(x||'Belum diisi')}</p>`).join('')}</section>`}${data.archives.length?`<section class="card"><h3>Arsip Siklus</h3>${data.archives.map((a,i)=>`<button class="menu-row" onclick="archiveIndex=${i};route='cycle';render()">${formatDate(a.startDate)} – ${formatDate(Method.bounds(a).end)} ${icon('right')}</button>`).join('')}<button class="text-btn" onclick="archiveIndex=-1;render()">Kembali ke siklus aktif</button></section>`:''}`,'Review 90 Hari','Hasil, perubahan, dan bekal untuk langkah berikutnya.');}
function saveCycleReview(e){e.preventDefault();data.cycleReview=Object.fromEntries(new FormData(e.target));if(save())toast('Review 90 hari tersimpan.');}
function beginNewCycle(){if(todayKey()<Method.bounds(data).end)return;if(timer){toast('Akhiri sesi fokus sebelum memulai siklus baru.');return;}dialogForm('Mulai siklus baru?','Siklus ini beserta target, MIT, sesi fokus, dan review akan diarsipkan. Siklus baru dimulai hari ini dengan target dan rencana kosong.','',()=>{syncToday();const next=Method.newCycle(data);try{localStorage.setItem(STORAGE_KEY+'-before-new-cycle',JSON.stringify(data));localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{toast('Arsip belum dapat disimpan. Unduh backup terlebih dahulu.');return;}data=next;focusMitId='';selectedDate=todayKey();weekOffset=0;archiveIndex=-1;closeDialog();go('goals');toast('Siklus baru dimulai. Arsip tersedia di Review 90 Hari.');},'Mulai Siklus Baru');}
function more(){return shell(`${[['weekly','calendar','Fokus Mingguan','Pilih 3 hasil penting untuk minggu ini.'],['review','book','Review Mingguan','Lihat hasil dan putuskan strategi.'],['cycle','target','Review 90 Hari','Lihat capaian dan arsip siklus.'],['failure','alert','Jurnal Kegagalan','Belajar dari hal yang belum berjalan baik.'],['rewards','gift','Reward & Konsekuensi','Rayakan progres, jaga komitmen.'],['settings','settings','Profil & Pengaturan','Data, backup, tema, dan kebiasaan.']].map(([r,i,t,s])=>`<button class="card more-card" onclick="${r==='weekly'||r==='review'?'weekOffset=0;':''}go('${r}')"><span class="icon-disc">${icon(i)}</span><span class="label"><b>${t}</b><small>${s}</small></span>${icon('right')}</button>`).join('')}`,'Lainnya','Review adalah tempat memperbaiki strategi.');}
function editProfile(){dialogForm('Edit profil','Tanggal mulai menentukan batas siklus. Riwayat tetap tersimpan.',field('Nama kamu','name',data.name,'text','required maxlength="40"')+field('Tanggal mulai 90 hari','startDate',data.startDate,'date',`required max="${todayKey()}"`),f=>{const name=f.get('name').trim(),start=f.get('startDate');if(!name||!Method.validDate(start))return;const oldEnd=Method.bounds(data).end;data.name=name;data.startDate=start;for(const g of data.goals)if(g.deadline===oldEnd||g.deadline<start||g.deadline>Method.bounds(data).end)g.deadline=Method.bounds(data).end;save();closeDialog();render();});}
function habitSettings(){dialogForm('Pengaturan habit','Bangun kebiasaan yang dapat diulang.',field('Kebiasaan utama','habit',data.today.habitText,'text','required maxlength="150"')+selectField('Durasi fokus default','duration',[['25','25 menit'],['50','50 menit']],String(data.settings.focusMinutes)),f=>{data.today.habitText=f.get('habit').trim();data.settings.focusMinutes=Number(f.get('duration'));syncToday();save();closeDialog();render();});}
function downloadJSON(value,name){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportBackup(){syncToday();downloadJSON({format:'skd90-backup',version:2,exportedAt:new Date().toISOString(),data},`SKD90-Method-backup-${todayKey()}.json`);toast('Backup lengkap disiapkan.');}
function exportOriginal(){const raw=localStorage.getItem(storageBlocked?STORAGE_KEY:STORAGE_KEY+'-before-method');if(raw)downloadJSON(raw,`SKD90-sebelum-upgrade-${todayKey()}.json`);else toast('Tidak ada salinan sebelum upgrade.');}
function backupSettings(){const checkpoints=[['before-method','Sebelum upgrade Method'],['before-import','Sebelum impor terakhir'],['before-reset','Sebelum reset terakhir'],['before-new-cycle','Sebelum siklus baru']].filter(([k])=>localStorage.getItem(STORAGE_KEY+'-'+k));dialogForm('Data & Backup','Data tersimpan di browser perangkat ini. Backup mencakup seluruh MIT, target, milestone, fokus mingguan, sesi fokus, review, jurnal, dan arsip siklus.',`<button type="button" class="btn soft full" onclick="exportBackup()">Unduh Backup Lengkap (.json)</button><button type="button" class="text-btn space" onclick="exportOriginal()">Unduh data asli sebelum upgrade</button><label class="reviewQ space"><b>Pulihkan dari backup</b><input class="input" type="file" accept=".json,application/json" onchange="importBackup(this.files[0])"></label>${checkpoints.length?`<details class="space"><summary>Cadangan otomatis di browser</summary>${checkpoints.map(([k,t])=>`<button type="button" class="menu-row" onclick="restoreCheckpoint('${k}')">${t}</button>`).join('')}</details>`:''}<button type="button" class="text-btn danger-text space" onclick="resetAll()">Reset semua data</button>`,()=>closeDialog(),'Selesai');}
function restoreCheckpoint(key){const raw=localStorage.getItem(STORAGE_KEY+'-'+key);if(raw)importBackup({size:raw.length,text:async()=>raw});}
async function importBackup(file){if(!file)return;try{if(file.size>20e6)throw Error('File terlalu besar (maksimal 20 MB).');const safe=Method.backup(JSON.parse(await file.text()));delete safe.activeTimer;delete safe.pendingFocus;closeDialog();dialogForm('Pulihkan backup?',`${safe.goals.length} target · ${Object.keys(safe.history).length} hari · ${safe.archives.length} arsip siklus. Data sekarang akan disalin sebagai cadangan sebelum diganti.`, '',()=>{try{const old=localStorage.getItem(STORAGE_KEY);if(old)localStorage.setItem(STORAGE_KEY+'-before-import',old);safe.onboarded=true;localStorage.setItem(STORAGE_KEY,JSON.stringify(safe));}catch{toast('Backup belum dipulihkan: penyimpanan tidak tersedia.');return;}data=safe;timer=null;focusMitId='';storageBlocked=false;loadError='';selectedDate=todayKey();weekOffset=0;closeDialog();go('home');toast('Backup lengkap berhasil dipulihkan.');},'Pulihkan');}catch(e){toast('Backup tidak valid. '+e.message);}}
function resetAll(){closeDialog();dialogForm('Reset semua data?','Data sekarang akan dicadangkan di browser sebelum diganti. Unduh backup untuk menyimpan salinan terpisah.',`<button type="button" class="btn soft full" onclick="exportBackup()">Unduh Backup Dulu</button>`,()=>{const fresh=Method.migrate({...defaults,goals:[],startDate:todayKey(),todayDate:todayKey()});try{const old=localStorage.getItem(STORAGE_KEY);if(old)localStorage.setItem(STORAGE_KEY+'-before-reset',old);localStorage.setItem(STORAGE_KEY,JSON.stringify(fresh));}catch{toast('Reset dibatalkan karena cadangan belum bisa disimpan.');return;}data=fresh;timer=null;focusMitId='';loadError='';storageBlocked=false;selectedDate=todayKey();weekOffset=0;closeDialog();go('home');},'Reset Data');}
function aboutApp(){dialogForm('SKD90 Method v1.0','Sistem Kendali Diri 90 Hari',`<p class="space">Target → Milestone → Fokus Mingguan → MIT → Eksekusi → Review → Adaptasi.</p><p class="space">Target adalah hasil. Milestone adalah arah. Weekly Focus adalah prioritas. MIT adalah tindakan. Review adalah tempat memperbaiki strategi.</p><p class="space mini">Execution = MIT selesai ÷ MIT terisi. Result = (aktual − nilai awal) ÷ (sasaran − nilai awal). Konsistensi = minimal 4/5 kebiasaan harian. Data lokal; dapat digunakan offline setelah pemuatan pertama.</p>`,()=>closeDialog(),'Mengerti');}
function render(){rollover();document.documentElement.dataset.theme=data.settings.theme;const pages={home,focus,goals,stats,more,weekly,review,cycle,failure,detail,rewards,settings};document.getElementById('app').innerHTML=data.onboarded?(pages[route]||home)():splash();if(data.onboarded&&route==='focus')updateTimerDisplay();document.title='SKD90 Method v1.0';}
// Synchronize tabs before accepting another write, preventing stale-tab overwrite.
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue){try{data=Method.migrate(JSON.parse(e.newValue));timer=data.activeTimer||null;focusMode=timer?.mode||focusMode;if(document.getElementById('dialog').open)closeDialog();render();toast('Data diperbarui dari tab lain.');}catch{toast('Data dari tab lain tidak dapat dibaca.');}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();if(data.todayDate!==todayKey())render();}});
if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
data.onboarded=false;
if(!storageBlocked)save();
render();
setInterval(tick,500);
